// npm run help:build — compiles the user-facing knowledge base.
//
//  docs/help/*.md (one per page, front-matter: page_route/title/updated/
//  keywords) + docs/help/_limitations.md  ──►
//    1. docs/help/_digest.md            — the chatbot's knowledge payload
//       (date + version + commit stamped, limitations up top);
//    2. lib/help-content.generated.ts   — the same content as a typed module
//       bundled into the app (help drawer, /help, /api/support-chat) so
//       nothing is fetched at runtime;
//    3. COVERAGE CHECK: every route in lib/nav-links.ts and
//       app/reports/reports-nav.ts must resolve to a help topic (longest
//       route-prefix match) — a page without help FAILS the build. The
//       vitest suite runs the same check, so CI enforces it too.
//
// Session-end ritual: update the affected docs/help pages alongside
// PROJECT_SUMMARY.md, then run `npm run help:build` and commit the outputs.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const helpDir = join(root, 'docs', 'help')

function parseFrontMatter(raw, file) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/)
  if (!m) throw new Error(`${file}: missing front-matter`)
  const meta = {}
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^(\w+):\s*(.*)$/)
    if (kv) meta[kv[1]] = kv[2].trim()
  }
  for (const key of ['page_route', 'title', 'updated', 'keywords']) {
    if (!meta[key]) throw new Error(`${file}: front-matter is missing "${key}"`)
  }
  return { meta, body: m[2].trim() }
}

const topicFiles = readdirSync(helpDir).filter((f) => f.endsWith('.md') && !f.startsWith('_')).sort()
if (topicFiles.length === 0) {
  console.error('docs/help has no topic files.')
  process.exit(1)
}
const topics = topicFiles.map((f) => {
  const { meta, body } = parseFrontMatter(readFileSync(join(helpDir, f), 'utf8'), f)
  return { file: f, route: meta.page_route, title: meta.title, updated: meta.updated, keywords: meta.keywords, body }
})

const dupes = topics.filter((t, i) => topics.findIndex((x) => x.route === t.route) !== i)
if (dupes.length > 0) {
  console.error(`Duplicate page_route in help files: ${dupes.map((d) => `${d.file} (${d.route})`).join(', ')}`)
  process.exit(1)
}

// ---- Coverage: every nav/report route must resolve to a topic. ----
const routeSources = [
  readFileSync(join(root, 'lib', 'nav-links.ts'), 'utf8'),
  readFileSync(join(root, 'app', 'reports', 'reports-nav.ts'), 'utf8'),
]
const appRoutes = new Set()
for (const src of routeSources) {
  for (const m of src.matchAll(/href:\s*'([^']+)'/g)) appRoutes.add(m[1])
}
const topicForRoute = (route) => {
  let best = null
  for (const t of topics) {
    const covers = route === t.route || route.startsWith(t.route === '/' ? '/' : t.route + '/')
    if (covers && (best == null || t.route.length > best.route.length)) best = t
  }
  // '/' only covers exactly '/'.
  if (best && best.route === '/' && route !== '/') return null
  return best
}
const uncovered = [...appRoutes].filter((r) => !topicForRoute(r))
if (uncovered.length > 0) {
  console.error('HELP COVERAGE FAILED — these routes have no help topic (add a docs/help file):')
  for (const r of uncovered) console.error(`  ${r}`)
  process.exit(1)
}

// ---- Stamp + outputs. ----
let commit = 'unknown'
try { commit = execSync('git rev-parse --short HEAD', { cwd: root }).toString().trim() } catch { /* shallow env */ }
const version = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version ?? '0.0.0'
const generated = new Date().toISOString().slice(0, 10)
const limitations = readFileSync(join(helpDir, '_limitations.md'), 'utf8').trim()

const digest = [
  `# Turnrow capabilities digest`,
  ``,
  `Generated ${generated} · version ${version} · build ${commit}. Compiled from docs/help — regenerate with \`npm run help:build\`.`,
  ``,
  limitations,
  ``,
  ...topics.flatMap((t) => [`# ${t.title}  (page: ${t.route})`, ``, t.body, ``]),
].join('\n')
writeFileSync(join(helpDir, '_digest.md'), digest)

const moduleSrc = `// GENERATED by scripts/build-help.mjs — do not edit. Run: npm run help:build
/* eslint-disable */
export type HelpTopic = { route: string; title: string; updated: string; keywords: string; body: string }
export const HELP_GENERATED = ${JSON.stringify(generated)}
export const HELP_VERSION = ${JSON.stringify(`${version}+${commit}`)}
export const HELP_TOPICS: HelpTopic[] = ${JSON.stringify(
  topics.map(({ route, title, updated, keywords, body }) => ({ route, title, updated, keywords, body })),
  null,
  2,
)}
export const HELP_DIGEST: string = ${JSON.stringify(digest)}
`
writeFileSync(join(root, 'lib', 'help-content.generated.ts'), moduleSrc)

console.log(`help:build OK — ${topics.length} topics, ${appRoutes.size} routes covered, digest ${Math.round(digest.length / 1024)} KB (${generated} ${commit})`)
